"""add staff login fields

Revision ID: da942c3c1695
Revises: 
Create Date: 2026-06-14 15:10:01.572468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da942c3c1695'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_staff_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint('uq_staff_username', type_='unique')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')


    # ### end Alembic commands ###
